/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WorkBoschBcwRouteImport } from './routes/work.bosch-bcw'
import { Route as WorkCityloopRouteImport } from './routes/work.cityloop'
import { Route as WorkFieldkitRouteImport } from './routes/work.fieldkit'
import { Route as WorkInfosysRouteImport } from './routes/work.infosys'
import { Route as WorkMytownRouteImport } from './routes/work.mytown'
import { Route as WorkPlaypalRouteImport } from './routes/work.playpal'
import { Route as WorkTalosCareRouteImport } from './routes/work.talos-care'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBoschBcwRoute = WorkBoschBcwRouteImport.update({
  id: '/work/bosch-bcw',
  path: '/work/bosch-bcw',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCityloopRoute = WorkCityloopRouteImport.update({
  id: '/work/cityloop',
  path: '/work/cityloop',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFieldkitRoute = WorkFieldkitRouteImport.update({
  id: '/work/fieldkit',
  path: '/work/fieldkit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkInfosysRoute = WorkInfosysRouteImport.update({
  id: '/work/infosys',
  path: '/work/infosys',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkMytownRoute = WorkMytownRouteImport.update({
  id: '/work/mytown',
  path: '/work/mytown',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPlaypalRoute = WorkPlaypalRouteImport.update({
  id: '/work/playpal',
  path: '/work/playpal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTalosCareRoute = WorkTalosCareRouteImport.update({
  id: '/work/talos-care',
  path: '/work/talos-care',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/work/bosch-bcw': typeof WorkBoschBcwRoute
  '/work/cityloop': typeof WorkCityloopRoute
  '/work/fieldkit': typeof WorkFieldkitRoute
  '/work/infosys': typeof WorkInfosysRoute
  '/work/mytown': typeof WorkMytownRoute
  '/work/playpal': typeof WorkPlaypalRoute
  '/work/talos-care': typeof WorkTalosCareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/work/bosch-bcw': typeof WorkBoschBcwRoute
  '/work/cityloop': typeof WorkCityloopRoute
  '/work/fieldkit': typeof WorkFieldkitRoute
  '/work/infosys': typeof WorkInfosysRoute
  '/work/mytown': typeof WorkMytownRoute
  '/work/playpal': typeof WorkPlaypalRoute
  '/work/talos-care': typeof WorkTalosCareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/work/bosch-bcw': typeof WorkBoschBcwRoute
  '/work/cityloop': typeof WorkCityloopRoute
  '/work/fieldkit': typeof WorkFieldkitRoute
  '/work/infosys': typeof WorkInfosysRoute
  '/work/mytown': typeof WorkMytownRoute
  '/work/playpal': typeof WorkPlaypalRoute
  '/work/talos-care': typeof WorkTalosCareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/work/bosch-bcw'
    | '/work/cityloop'
    | '/work/fieldkit'
    | '/work/infosys'
    | '/work/mytown'
    | '/work/playpal'
    | '/work/talos-care'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/work/bosch-bcw'
    | '/work/cityloop'
    | '/work/fieldkit'
    | '/work/infosys'
    | '/work/mytown'
    | '/work/playpal'
    | '/work/talos-care'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/work/bosch-bcw'
    | '/work/cityloop'
    | '/work/fieldkit'
    | '/work/infosys'
    | '/work/mytown'
    | '/work/playpal'
    | '/work/talos-care'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WorkBoschBcwRoute: typeof WorkBoschBcwRoute
  WorkCityloopRoute: typeof WorkCityloopRoute
  WorkFieldkitRoute: typeof WorkFieldkitRoute
  WorkInfosysRoute: typeof WorkInfosysRoute
  WorkMytownRoute: typeof WorkMytownRoute
  WorkPlaypalRoute: typeof WorkPlaypalRoute
  WorkTalosCareRoute: typeof WorkTalosCareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/bosch-bcw': {
      id: '/work/bosch-bcw'
      path: '/work/bosch-bcw'
      fullPath: '/work/bosch-bcw'
      preLoaderRoute: typeof WorkBoschBcwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/cityloop': {
      id: '/work/cityloop'
      path: '/work/cityloop'
      fullPath: '/work/cityloop'
      preLoaderRoute: typeof WorkCityloopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/fieldkit': {
      id: '/work/fieldkit'
      path: '/work/fieldkit'
      fullPath: '/work/fieldkit'
      preLoaderRoute: typeof WorkFieldkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/infosys': {
      id: '/work/infosys'
      path: '/work/infosys'
      fullPath: '/work/infosys'
      preLoaderRoute: typeof WorkInfosysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/mytown': {
      id: '/work/mytown'
      path: '/work/mytown'
      fullPath: '/work/mytown'
      preLoaderRoute: typeof WorkMytownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/playpal': {
      id: '/work/playpal'
      path: '/work/playpal'
      fullPath: '/work/playpal'
      preLoaderRoute: typeof WorkPlaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/talos-care': {
      id: '/work/talos-care'
      path: '/work/talos-care'
      fullPath: '/work/talos-care'
      preLoaderRoute: typeof WorkTalosCareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WorkBoschBcwRoute: WorkBoschBcwRoute,
  WorkCityloopRoute: WorkCityloopRoute,
  WorkFieldkitRoute: WorkFieldkitRoute,
  WorkInfosysRoute: WorkInfosysRoute,
  WorkMytownRoute: WorkMytownRoute,
  WorkPlaypalRoute: WorkPlaypalRoute,
  WorkTalosCareRoute: WorkTalosCareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
